name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4.1.1
      - id: setup-bun
        name: Setup Bun
        uses: oven-sh/setup-bun@v1.1.1
        with:
          bun-version: latest
      - id: install-deps
        name: Install dependencies
        run: |
          bun install
      - id: lint
        name: Run lint
        run: |
          bun lint
      - id: test
        name: Run test
        run: |
          bun test
