name: NPM publish
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - id: setup-bun
        name: Setup Bun
        uses: oven-sh/setup-bun@v1.1.1
        with:
          bun-version: latest
      - id: install-deps
        name: Install dependencies
        run: |
          bun install
      - id: lint
        name: Run lint
        run: |
          bun lint
      - id: test
        name: Run test
        run: |
          bun test
      - id: build
        name: Run build
        run: |
            bun run build

      - uses: JS-DevTools/npm-publish@v3.0.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
